<a href="https://colab.research.google.com/github/0bsidian03/CompPhysHW/blob/main/Hw3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [6]:

A = np.array([[1, 2], [3, -1]])
B = np.array([[3, -2], [2, 1]])
C = np.array([[1], [2], [3]])
D = np.array([[1, 3, 1], [-2, 1, -1]])
E = np.array([[3, 1], [0, 3], [-2, 2]])
F = np.array([[2, 1, 2], [-1, 3, -2]])

print("Matrix A:", A)
print("Matrix B:", B)
print("Matrix C:", C)
print("Matrix D:", D)
print("Matrix E:", E)
print("Matrix F:", F)

Matrix A: [[ 1  2]
 [ 3 -1]]
Matrix B: [[ 3 -2]
 [ 2  1]]
Matrix C: [[1]
 [2]
 [3]]
Matrix D: [[ 1  3  1]
 [-2  1 -1]]
Matrix E: [[ 3  1]
 [ 0  3]
 [-2  2]]
Matrix F: [[ 2  1  2]
 [-1  3 -2]]


In [7]:
product_AB = A @ B
print("Product AB:", product_AB)
product_EF = E @ F
print("Product EF:", product_EF)

Product AB: [[ 7  0]
 [ 7 -7]]
Product EF: [[ 5  6  4]
 [-3  9 -6]
 [-6  4 -8]]


cd is not a valid matrix multiplication due to the dimensions

In [8]:

productATB = A.T @ B
print("Product A^TB:", productATB)


Product A^TB: [[ 9  1]
 [ 4 -5]]


the multiplications do not work because the matrices sizes are not valid after transposition

In [9]:
M = np.array([[1, 0, 1],
              [2, 2, 3],
              [1, 2, 4]])
Minv = np.linalg.inv(M)
print("Inverse of M:", Minv)
productMMinv = M @ Minv
print("Product M * M^-1:", productMMinv)




Inverse of M: [[ 0.5   0.5  -0.5 ]
 [-1.25  0.75 -0.25]
 [ 0.5  -0.5   0.5 ]]
Product M * M^-1: [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [10]:
Praw = np.array([[3, -2, -6],
                  [-6, -3, -2],
                  [-2, 6, -3]])
P = (1/7) * Praw

print("Matrix P:", P)

Matrix P: [[ 0.42857143 -0.28571429 -0.85714286]
 [-0.85714286 -0.42857143 -0.28571429]
 [-0.28571429  0.85714286 -0.42857143]]


In [11]:
productPPT = P @ P.T
print("Product P * P^T:", productPPT)
productPTP = P.T @ P
print("\nProduct P^T * P:", productPTP)


Product P * P^T:
 [[ 1.00000000e+00  6.23084351e-18 -4.53152255e-18]
 [ 6.23084351e-18  1.00000000e+00 -1.07623661e-17]
 [-4.53152255e-18 -1.07623661e-17  1.00000000e+00]]

Product P^T * P:
 [[ 1.00000000e+00 -6.23084351e-18 -1.07623661e-17]
 [-6.23084351e-18  1.00000000e+00  4.53152255e-18]
 [-1.07623661e-17  4.53152255e-18  1.00000000e+00]]


machine precision so its not exact but its good enough

In [13]:
A = np.array([[-1, 3, 5, 2],
              [ 1, 9, 8, 4],
              [ 0, 1, 0, 1],
              [ 2, 1, 1, -1]])
b = np.array([[10],
              [15],
              [ 2],
              [-3]])
determinantA = np.linalg.det(A)
print("Determinant of A:", determinantA)
x = np.linalg.solve(A, b)
print(f"x1 = {x[0][0]:.4f}")
print(f"x2 = {x[1][0]:.4f}")
print(f"x3 = {x[2][0]:.4f}")
print(f"x4 = {x[3][0]:.4f}")



Determinant of A: 14.000000000000004
x1 = -1.0000
x2 = 0.0000
x3 = 1.0000
x4 = 2.0000


plug back in and you can confirm these values :)

In [19]:
A = np.array([[10, -1, 2, 0],
              [-1, 11, -1, 3],
              [2, -1, 10, -1],
              [0, 3, -1, 8]])
b1 = np.array([6, 25, -11, 15])
b2 = np.array([12, -11, 13, -1])
def gauss_seidel(A, b, x0, tol=1e-5, max_iterations=1000):
    n = len(b)
    x = x0.copy().astype(float)
    x_prev = np.zeros(n)
    iterations = 0
    for k in range(max_iterations):
        x_prev = x.copy()
        for i in range(n):
            sum1 = np.dot(A[i, :i], x[:i])
            sum2 = np.dot(A[i, i+1:], x_prev[i+1:])
            x[i] = (b[i] - sum1 - sum2) / A[i, i]
        if np.linalg.norm(x - x_prev, ord=2) < tol:
            iterations = k + 1
            return x, iterations
    iterations = max_iterations
    return x, iterations
n = len(b1)
x0_b1 = np.zeros(n)  # Initial guess as a zero vector
solution_b1, iterations_b1 = gauss_seidel(A, b1, x0_b1)
print("Solution for b1:", solution_b1)
print("Iterations for b1:", iterations_b1)
n = len(b2)
x0_b2 = np.zeros(n)  # Initial guess as a zero vector
solution_b2, iterations_b2 = gauss_seidel(A, b2, x0_b2)
print("Solution for b2:", solution_b2)
print("Iterations for b2:", iterations_b2)



Solution for b1: [ 1.00000067  2.00000002 -1.00000021  0.99999996]
Iterations for b1: 7
Solution for b2: [ 0.89533372 -0.91791806  1.06436819  0.35226529]
Iterations for b2: 6


the low number of iteration demonstrates why gauss-seidel is generally considered a very good method

In [38]:
A = np.array( [[0.780,0.563],[0.913,0.659]])
b = np.array([0.217,0.254])
xexact = np.array([1, -1])
xalpha = np.array([0.999, -1.001])
xbeta = np.array([0.34,-0.087])
ralpha = b - A @ xalpha
rbeta = b - A @ xbeta
magnituderalpha= np.linalg.norm(ralpha)
magnituderbeta= np.linalg.norm(rbeta)
print("Residual for xalpha:", ralpha)
print("Magnitude of residual for xalpha:", magnituderalpha)
print("Residual for xbeta:", rbeta)
print("Magnitude of residual for xbeta:", magnituderbeta)


Residual for xalpha: [0.001343 0.001572]
Magnitude of residual for xalpha: 0.0020675669275744407
Residual for xbeta: [0.000781 0.000913]
Magnitude of residual for xbeta: 0.0012014699330403214


the more accurate solution actually has a bigger residual

In [34]:
determinant_A = np.linalg.det(A)
print("Determinant of A:", determinant_A)

Determinant of A: 1.000000000122681e-06


its not zero but its very small which may make it effectively 0 at machine precision

In [36]:
solution_x = np.linalg.solve(A, b)
print( solution_x)

[ 1. -1.]


this is equal to the exact solution, so pythons pretty good

In [63]:
A = np.array([[3, 1, 2],
              [1, 5, 3],
              [2, 3, 7]])
b = np.array([[-1],
              [1],
              [3]])
def gram_schmidt_qr(A):
    m, n = A.shape
    Q = np.zeros((m, n))
    R = np.zeros((n, n))
    for j in range(n):
        v = A[:, j]
        for i in range(j):
            q = Q[:, i]
            R[i, j] = np.dot(q, v)
            v = v - R[i, j] * q
        R[j, j] = np.linalg.norm(v)
        Q[:, j] = v / R[j, j]
    return Q, R

Q, R = gram_schmidt_qr(A)
print("Matrix Q:", Q)
print("Matrix R:", R)

Matrix Q: [[ 0.80178373 -0.43643578 -0.40824829]
 [ 0.26726124  0.87287156 -0.40824829]
 [ 0.53452248  0.21821789  0.81649658]]
Matrix R: [[3.74165739 3.74165739 6.14700856]
 [0.         4.58257569 3.27326835]
 [0.         0.         3.67423461]]


In [64]:
def back_substitution(R, y):
    n = len(y)
    x = np.zeros_like(y, dtype=float)
    for i in range(n - 1, -1, -1):
        sum_val = 0
        for j in range(i + 1, n):
            sum_val += R[i, j] * x[j]
        x[i] = (y[i] - sum_val) / R[i, i]
    return x

xqr = back_substitution(R, Q.T@b)
print("Solution x using QR decomposition:", xqr)

Solution x using QR decomposition: [[-0.76190476]
 [-0.04761905]
 [ 0.66666667]]


In [65]:
xreal = np.linalg.solve(A, b)
print("Solution x using np.linalg.solve:", xreal)


Solution x using np.linalg.solve: [[-0.76190476]
 [-0.04761905]
 [ 0.66666667]]


In [66]:
Mx =(1/2**-1)*np.array([[0, 1, 0], [1, 0, 1], [0, 1, 0]], dtype=complex)
My =(1/2**-1)* np.array([[0, -1j, 0], [1j, 0, -1j], [0, 1j, 0]], dtype=complex)
Mz = (1/2**-1)*np.array([[1, 0, 0], [0, 0, 0], [0, 0, -1]], dtype=complex)
print( Mx)
print( My)
print( Mz)

[[0.+0.j 2.+0.j 0.+0.j]
 [2.+0.j 0.+0.j 2.+0.j]
 [0.+0.j 2.+0.j 0.+0.j]]
[[0.+0.j 0.-2.j 0.+0.j]
 [0.+2.j 0.+0.j 0.-2.j]
 [0.+0.j 0.+2.j 0.+0.j]]
[[ 2.+0.j  0.+0.j  0.+0.j]
 [ 0.+0.j  0.+0.j  0.+0.j]
 [ 0.+0.j  0.+0.j -2.+0.j]]


In [67]:
iMz = 1j * Mz

print( "Mx*MY", Mx@My)
print("My*Mx",My@Mx)
print("[Mx,My]", Mx@My - My@Mx)
print("iMz", iMz)



Mx*MY [[0.+4.j 0.+0.j 0.-4.j]
 [0.+0.j 0.+0.j 0.+0.j]
 [0.+4.j 0.+0.j 0.-4.j]]
My*Mx [[0.-4.j 0.+0.j 0.-4.j]
 [0.+0.j 0.+0.j 0.+0.j]
 [0.+4.j 0.+0.j 0.+4.j]]
[Mx,My] [[0.+8.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.-8.j]]
iMz [[ 0.+2.j  0.+0.j  0.+0.j]
 [ 0.+0.j  0.+0.j  0.+0.j]
 [ 0.+0.j  0.+0.j -0.-2.j]]


In [68]:
Mxsquared = Mx @ Mx
Mysquared = My @ My
Mzsquared = Mz @ Mz

sumMsquared = Mxsquared + Mysquared + Mzsquared

identitymatrix = np.identity(3, dtype=complex)
twoidentitymatrix = 2 * identitymatrix

print("Mx^2:", Mxsquared)
print("My^2:", Mysquared)
print("Mz^2:", Mzsquared)
print("Sum of M_squared (Mx^2 + My^2 + Mz^2):", sumMsquared)
print("2 * Identity Matrix (2I):", twoidentitymatrix)

Mx^2: [[4.+0.j 0.+0.j 4.+0.j]
 [0.+0.j 8.+0.j 0.+0.j]
 [4.+0.j 0.+0.j 4.+0.j]]
My^2: [[ 4.+0.j  0.+0.j -4.+0.j]
 [ 0.+0.j  8.+0.j  0.+0.j]
 [-4.+0.j  0.+0.j  4.+0.j]]
Mz^2: [[4.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 4.+0.j]]
Sum of M_squared (Mx^2 + My^2 + Mz^2): [[12.+0.j  0.+0.j  0.+0.j]
 [ 0.+0.j 16.+0.j  0.+0.j]
 [ 0.+0.j  0.+0.j 12.+0.j]]
2 * Identity Matrix (2I): [[2.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 2.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 2.+0.j]]


unfortunately the above cells show these relationships as false, I don't know why, i suspect it's how i tried setting up my matrices, but ai was no help trying to fix it